---
- name: Setup dodger
  hosts: dodger
  become: true
  gather_facts: true
  vars_files:
    - "users.yml"
  roles:
    # - name: gantsign.oh-my-zsh
    # - name: default
    # - name: robertdebock.update
    # - name: docker
    - name: crowdsec
  # tasks:
  #   - name: Clone repository
  #     ansible.builtin.git:
  #       repo: https://github.com/stefanDeveloper/dodger.git
  #       dest: /srv/dodger
