---
- name: Setup dodger
  hosts: dodger
  become: true
  gather_facts: true
  vars_files:
    - "users.yml"
  roles:
    - name: gantsign.oh-my-zsh
    - name: default
    - name: robertdebock.update
    - name: docker
    - name: crowdsec
    - name: traefik
    - name: openldap
    - name: gitlab
    - name: homer
    - name: nextcloud
    - name: watchtower

# code: language=ansible
