---

- name: Start watchtower
  community.docker.docker_container:
    name: watchtower
    image: "containrrr/watchtower"
    restart_policy: "unless-stopped"
    env:
      DOCKER_API_VERSION: "1.52" # https://github.com/containrrr/watchtower/issues/2122
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      
# code: language=ansible
