---

- name: Create folder for nextcloud
  ansible.builtin.file:
    path: "{{ nextcloud_docker_path }}"
    state: directory
    mode: 0700
    owner: "{{ dodger_user }}"
    group: "{{ dodger_group }}"

- name: Create Postgres DB Container
  community.docker.docker_container: # 999:999
    name: nextcloud_postgres
    hostname: nextcloud_postgres
    image: postgres:13
    restart_policy: unless-stopped
    recreate: True
    tty: true
    interactive: true
    command: "postgres -c 'max_connections=999'"
    networks:
      - name: proxy
    env:
      POSTGRES_USER: "{{ nextcloud_postgres_username }}"
      POSTGRES_PASSWORD: "{{ nextcloud_postgres_password }}"
      POSTGRES_DB: "{{ nextcloud_postgres_db }}"
    volumes:
      - "{{ nextcloud_docker_path }}/nextcloud-db:/var/lib/postgresql/data"

- name: Create Redis Container
  community.docker.docker_container:
    name: nextcloud_redis
    hostname: nextcloud_redis
    restart_policy: unless-stopped
    image: redis:latest
    command: "redis-server --requirepass {{ nextcloud_redis_password }}"
    networks:
      - name: proxy
    volumes:
      - "{{ nextcloud_docker_path }}/redis:/var/lib/redis"

- name: Create ClamAV Container
  community.docker.docker_container:
    name: "nextcloud_clamav"
    hostname: "nextcloud_clamav"
    image: "clamav/clamav:stable_base"
    networks:
      - name: proxy
    volumes:
      - "{{ nextcloud_docker_path }}/clamav/virus_db/:/var/lib/clamav/"
    restart_policy: unless-stopped

- name: Create Nextcloud container
  community.docker.docker_container: # 33:root
    name: "nextcloud"
    hostname: "nextcloud"
    image: "nextcloud:latest"
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: proxy
        ipv4_address: 172.18.0.5
    env:
      POSTGRES_DB: "{{ nextcloud_postgres_db }}"
      POSTGRES_USER: "{{ nextcloud_postgres_username }}"
      POSTGRES_PASSWORD: "{{ nextcloud_postgres_password }}"
      POSTGRES_HOST: "nextcloud_postgres"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      REDIS_HOST: "nextcloud_redis"
      REDIS_HOST_PASSWORD: "{{ nextcloud_redis_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_domain }}"
      TRUSTED_PROXIES: "172.18.0.0/16"
      OVERWRITEPROTOCOL: "https"
    volumes:
      - "{{ nextcloud_docker_path }}/nextcloud-www:/var/www/html"

- name: Write nextcloud background job
  ansible.builtin.cron:
    name: nextcloud_background_job
    user: root
    job: /usr/local/bin/docker exec -u www-data nextcloud php /var/www/html/cron.php >/var/logs/cron.log 2>/var/log/cron_error.log
    # */5 * * * *
    minute: "*/5"

# - name: Update DNS
#   ansible.builtin.cron:
#     name: dns_background_job
#     user: macau
#     job: /usr/local/bin/php /Users/macau/dynamic-dns-netcup-api/update.php
#     # */5 * * * *
#     minute: "*/5"

# code: language=ansible
