version: "3.3"

services:
  mautrix-telegram:
    container_name: mautrix-telegram
    image: dock.mau.dev/mautrix/telegram:latest
    restart: unless-stopped
    volumes:
      - ./matrix-synapse-files/matrix-telegram:/data
    networks:
      - proxy

  mautrix-telegram-db:
    container_name: matrix-telegram-db
    image: docker.io/postgres:12-alpine
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./matrix-telegram-schemas:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    external: true