---
- name: OS and SSH Hardening using devsec
  ansible.builtin.include_tasks: "hardening.yml"

- name: Install common software
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - htop
    - vim

# code: language=ansible
