version: '3.3'
services:
  db:
    restart: always
    image: postgres:11
    networks:
      - proxy
    environment:
    - POSTGRES_USER=nextcloud
    - POSTGRES_PASSWORD=${POSTGRES_PW}
    - POSTGRES_DB=nextcloud
    volumes:
    - ./nextcloud-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PW}
    networks:
      - proxy
    volumes:
      - ./redis:/var/lib/redis

  nextcloud:
    image: nextcloud:latest
    restart: always
    hostname: nextcloud.${DOMAIN}
    networks:
      - proxy
    depends_on:
      - redis
      - db
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect
      - traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      # - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://${DOMAIN}
      # - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} *.${DOMAIN}
      # - traefik.http.middlewares.testHeader.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_PW}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${POSTGRES_PW}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PW}
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${DOMAIN}
      - TRUSTED_PROXIES=172.18.0.0/16
      - OVERWRITEPROTOCOL=https
    volumes:
      - ./nextcloud-www:/var/www/html

networks:
  proxy:
    external: true