version: '3.3'
services:
  db:
    restart: always
    image: postgres:13
    container_name: "nextcloud_postgres"
    networks:
      - proxy
    environment:
    - POSTGRES_USER=nextcloud
    - POSTGRES_PASSWORD=${POSTGRES_PW}
    - POSTGRES_DB=nextcloud
    volumes:
    - ./nextcloud-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: "nextcloud_redis"
    restart: always
    command: redis-server --requirepass ${REDIS_PW}
    networks:
      - proxy
    volumes:
      - ./redis:/var/lib/redis

  clamav:
    image: "clamav/clamav:stable_base"
    container_name: "clamav"
    networks:
      - proxy
    volumes:
      # Socket
      # - /usr/sbin/:/var/run/clamav/
      # Virus DB
      - /var/docker/clamav/virus_db/:/var/lib/clamav/
    ports:
      - 3310:3310
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    restart: always
    container_name: "nextcloud"
    hostname: nextcloud.${DOMAIN}
    networks:
      - proxy
    depends_on:
      - redis
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud-dav
      - traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://${DOMAIN}
      - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} *.${DOMAIN}
      - traefik.http.middlewares.nextcloud.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.replacement=https://$${1}/remote.php/dav/"
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_PW}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${POSTGRES_PW}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PW}
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${DOMAIN}
      - TRUSTED_PROXIES=172.18.0.0/16
      - OVERWRITEPROTOCOL=https
    volumes:
      - ./nextcloud-www:/var/www/html

networks:
  proxy:
    external: true