---
- name: Create folder for homer
  ansible.builtin.file:
    path: "{{ homer_docker_path }}"
    state: directory
    mode: 0700
    owner: stefan
    group: stefan

- name: Set homer config
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ homer_docker_path }}/config.yml"
    mode: 0700
    owner: stefan
    group: stefan

- name: Install homer Docker Container
  community.docker.docker_container:
    name: "homer"
    hostname: "homer"
    image: b4bz/homer
    restart_policy: unless-stopped
    volumes:
      - "{{ homer_docker_path }}/config.yml:/www/assets/config.yml:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homer.rule: "Host(`{{ homer_domain }}`)"
      traefik.http.routers.homer.entrypoints: "websecure"
      traefik.http.routers.homer.tls.certresolver: "mytlschallenge"
      traefik.http.services.homer.loadbalancer.server.port: "8080"
      traefik.http.routers.homer.middlewares: "homer-auth"
      traefik.http.middlewares.homer-auth.basicauth.users: "admin:{SHA}{{ traefik_dashboard_password }}"
    env:
      UID: "1000"
      GID: "1000"
      INIT_ASSETS: "1"
    networks:
      - name: "{{ traefik_network }}"

# code: language=ansible
