version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    privileged: true
    user: root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${DOMAIN}`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=mytlschallenge"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    environment:
      # you can set your preferred time zone
      - "TZ= Europe/Berlin"
      - "JAVA_OPTS=-Dhudson.footerURL=https://jenkins.${DOMAIN}"
    networks:
      - proxy
networks:
  proxy:
    external: true