version: '3.3'

services: 
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes: 
      - ./db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
  wordpress:
    links:
      - db 
    depends_on: 
      - db

    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWOR}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.me.rule=Host(`me.${DOMAIN}`)"
      - "traefik.http.routers.me.entrypoints=websecure"
      - "traefik.http.routers.me.tls.certresolver=mytlschallenge"
    networks:
      - proxy
networks:
  proxy:
    external: true
